import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="Outlook Mail Analytics", layout="wide")

# ---------- LOAD DATA ----------
per_day = pd.read_csv("mail_counts_per_day.csv")
per_week = pd.read_csv("mail_counts_per_week.csv")

per_day["date"] = pd.to_datetime(per_day["date"])
per_week["week_start"] = (
    pd.to_datetime(per_week["year"].astype(str) + "-W" + per_week["week"].astype(str) + "-1",
                   format="%G-W%V-%u")
)

# if you have raw data, the heatmap will be more accurate
raw_available = False
try:
    df = pd.read_csv("mail_raw.csv")
    df["datetime"] = pd.to_datetime(df["datetime"])
    raw_available = True
except FileNotFoundError:
    df = None

# ---------- SIDEBAR FILTERS ----------
st.sidebar.header("Filters")
directions = st.sidebar.multiselect(
    "Direction", options=per_day["direction"].unique().tolist(),
    default=per_day["direction"].unique().tolist()
)
start = st.sidebar.date_input("From", per_day["date"].min().date())
end = st.sidebar.date_input("To", per_day["date"].max().date())

mask = (
    per_day["direction"].isin(directions) &
    (per_day["date"].dt.date >= start) &
    (per_day["date"].dt.date <= end)
)
pd_f = per_day[mask].copy()

# ---------- KPI ROW ----------
total_in = per_day[per_day.direction=="incoming"]["count"].sum()
total_out = per_day[per_day.direction=="outgoing"]["count"].sum()
total = total_in + total_out

col1, col2, col3, col4 = st.columns(4)
col1.metric("Total mails", f"{total:,}".replace(",", " "))
col2.metric("Incoming", f"{total_in:,}".replace(",", " "))
col3.metric("Outgoing", f"{total_out:,}".replace(",", " "))
col4.metric("In/Out ratio", f"{total_in/total_out:.2f}" if total_out else "∞")

st.divider()

# ---------- 1) DAILY TREND ----------
st.subheader("Daily trend")
pd_plot = pd_f.pivot_table(index="date", columns="direction", values="count", fill_value=0)

# MA30
for c in pd_plot.columns:
    pd_plot[c + "_ma30"] = pd_plot[c].rolling(30, min_periods=1).mean()

fig = px.line(pd_plot, x=pd_plot.index, y=pd_plot.columns,
              labels={"value":"mail count", "date":"date"},
              title="Daily counts + MA30")
st.plotly_chart(fig, use_container_width=True)

# ---------- 2) WEEKLY COUNTS ----------
st.subheader("Weekly counts")
pw_f = per_week[per_week["direction"].isin(directions)].copy()
fig2 = px.bar(
    pw_f, x="week_start", y="count", color="direction", barmode="group",
    labels={"week_start":"week", "count":"count"},
    title="Mail counts per week"
)
st.plotly_chart(fig2, use_container_width=True)

# ---------- 3) HEATMAP DAY x HOUR ----------
st.subheader("Weekly rhythm (day × hour)")
if raw_available:
    df_f = df[df["direction"].isin(directions)].copy()
    df_f["hour"] = df_f["datetime"].dt.hour
    df_f["weekday"] = df_f["datetime"].dt.day_name()

    for direction in directions:
        sub = df_f[df_f.direction==direction]
        mat = sub.groupby(["weekday","hour"]).size().reset_index(name="count")
        pivot = mat.pivot(index="weekday", columns="hour", values="count").fillna(0)
        # order days
        order = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
        pivot = pivot.reindex(order)

        fig3 = px.imshow(
            pivot, aspect="auto",
            labels=dict(x="hour", y="weekday", color="count"),
            title=f"Heatmap: {direction}"
        )
        st.plotly_chart(fig3, use_container_width=True)
else:
    st.info("Heatmap requires mail_raw.csv (with timestamps of individual emails).")

st.caption("Data are loaded from CSVs generated by the COM script.")
